name: Build and Deploy

on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - continue-on-error: false
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Build
      - name: Run Build
        run: npm run build:prod

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-artifacts
          path: ./dist/${{secrets.APPNAME}}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: "build-artifacts"

      - name: Create bundle
        run: |
          cd ./build-artifacts
          mv ./deploy.sh ../
          tar -cvf ./${{secrets.APPNAME}}.tar ./*
          cd ../

      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.2
        with:
          service_account_email: ${{secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL}}
          service_account_key: ${{secrets.GCLOUD_SERVICE_ACCOUNT_KEY}}
          project_key: ${{secrets.GCLOUD_PROJECT}}

      - name: Deploy via SCP
        env:
          USERNAME: ${{secrets.USERNAME}}
          HOSTNAME: ${{secrets.HOSTNAME}}
          BASEPATH: ${{secrets.BASE_PATH}}
          APPNAME: ${{secrets.APPNAME}}
        run: |
          gcloud config list
